### PR TITLE
Fix documentation included in the Dockerfile

### PR DESCRIPTION
**Pull request by gfenoy**
We discovered that we are no more able to build using the current teamengine github repo. So, we decided to update the documentation on how to build and run locally the ETS for OGC API - Processes.

### CODE REVIEW

**Comment by ghobona** [comment]
@gfenoy Have you tried building using the instructions at https://github.com/opengeospatial/ets-ogcapi-processes10#how-to-run-the-test-suite-using-docker ?

**Comment by gfenoy** [comment]
@ghobona Unfortunately, I don't have Maven on my computer. So, I was not able to give it a try.

**Comment by ghobona** [comment]
@gfenoy Ok, we'll review the PR and look to update the documentation for building without Maven installed.

**Comment by gfenoy** [comment]
@ghobona Actually, we have moved the Dockerfile to the ZOO-Project repository.

This way the TeamEngine and this specific ETS can be build and run from the GitHub Action to provide testing results directly from [there](https://github.com/ZOO-Project/ZOO-Project/actions/runs/5081900339/jobs/9130902186#step:12:1341).

Obviously, it would probably be better to avoid building them from scratch every time. But we would like to keep in-sync with the latest version currently available in this GitHub repository to ensure future testing on the official ETS, once a new version will be updated on beta cite. Is there any place where we can find latest binary Docker image to use which is up-to-date with this repository?

**Comment by ghobona** [comment]
The [official docker image](https://hub.docker.com/r/ogccite/ets-ogcapi-processes10) is updated only when a Beta version is released.

**Review by bpross-52n — APPROVED** [review]

**Pull request merged**
